fix: Set default configuration value to prevent service panic error
edgexfoundry/device-mqtt-go pull request #177
Opened 2020-10-14 08:15 UTC by weichou1229

Fix #160

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
The service will panic if IncomingUser is missing from the configuration.

Issue Number: #160

## What is the new behavior?
Set default values before loading the config

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any new imports or modules? If so, what are they used for and why?

## Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2020-10-22 14:13 UTC, tonyespy requested changes
While this PR fixes the issue, my opinion is that it goes a bit too far by introducing the idea of default configuration values for the **Driver** options.

It should be possible to modify the code to simply not crash when `incomingUser`, or `incomingPassword`, or in fact any of the **Driver** options are not specified vs. modifying the code to define default values for all.

We had a big discussion about having default values for config items set in code at our last real face to face meeting in AZ last Fall. The problem with having defaults in the code, is that the default are not easily discoverable, and thus documentation has to be kept in-sync with the code.

If we want to go in this direction, then I think it needs to be first discussed in the architects meeting, and a consensus reached. As it is with your PR, only the Driver options have defaults, which means the service doesn't have consistent default across all configuration options. Also, AFAIK, this would be the only EdgeX service using this approach to-date.

@cloudxxx8 @lenny-intel thoughts?

2020-10-23 18:13 UTC, lenny-intel commented
> It should be possible to modify the code to simply not crash when `incomingUser`, or `incomingPassword`

I agree with @tonyespy . The parsing of the drive setting should be done at start-up and the service should exit with error message if required settings are missing.

2020-10-26 05:22 UTC, cloudxxx8 commented
how about we just shutdown the service without panic for now?

2020-10-26 05:27 UTC, weichou1229 commented
Close PR for furthermore discussion.

2020-10-26 05:27 UTC, closed without merging