feat: add UseMqttLevels capability to pass in metadata
edgexfoundry/device-mqtt-go pull request #303
Opened 2021-09-09 17:58 UTC by jenmwms

Closes #282

Signed-off-by:Jennifer Williams <jennifer.m.williams@intel.com>
Signed-off-by:Elizabeth J Lee <elizabeth.j.lee@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

###Related Docs PR now required (if applicable)
Related Docs PR:
https://github.com/edgexfoundry/edgex-docs/pull/566

## What is the current behavior?
Currently the MQTT device uses a payload that includes metadata for the device as a single-level topic.

## Issue Number:
Issue #282

## What is the new behavior?
Adds optional configuration for multi-level topics, which removes the metadata from the payload to leave only the values.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [x] Yes
- [ ] No

## Specific Instructions
Follow documentation to enable UseTopicLevels feature.

## Other information

2021-09-09 18:05 UTC, lenny-intel commented
@cloudxxx8 , note the related docs PR edgexfoundry/edgex-docs#566

2021-09-09 21:14 UTC, lenny-intel requested changes

2021-09-09 21:14 UTC, lenny-intel commented on go.mod
> -	gopkg.in/mgo.v2 v2.0.0-20190816093944-a6b53ec6cb22
@cloudxxx8 , this was old package that should have been replaced long ago.

2021-09-10 17:32 UTC, jenmwms commented on cmd/res/profiles/mqtt.test.device.profile.yml
> +  name: randfloat32andfloat64
Sounds good. Fixed!

2021-09-10 17:49 UTC, lenny-intel approved these changes
LGTM

2021-09-16 09:12 UTC, cloudxxx8 requested changes

2021-09-16 21:29 UTC, jenmwms commented on go.mod
> +	github.com/google/uuid v1.2.0
Updated now. Thanks!

2021-09-16 21:30 UTC, jenmwms commented on internal/driver/responselistener.go
> +		uuid = metaData[len(metaData)-1]
I've added a check if 0 to handle that case. Please let me know if this is headed in the right direction. Or did you have something else in mind to check if the length is correct?

2021-09-16 22:47 UTC, lenny-intel approved these changes
LGTM

2021-09-16 23:18 UTC, merged