refactor!: updated secret path to secretName
edgexfoundry/device-mqtt-go pull request #521
Opened 2023-03-10 17:59 UTC by vli11

BREAKING CHANGE: updated secret path to secretName

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-mqtt-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
make test
make docker

## New Dependency Instructions (If applicable)

2023-03-10 18:04 UTC, jim-wang-intel approved these changes
LGTM

2023-03-10 20:49 UTC, lenny-intel requested changes

2023-03-10 20:49 UTC, lenny-intel commented on cmd/res/configuration.toml
> +    secretName = "credentials"
```suggestion
    SecretName = "credentials"
```

2023-03-13 02:34 UTC, lenny-intel reviewed
LGTM  once tested

2023-03-13 17:02 UTC, lenny-intel approved these changes
LGTM

2023-03-13 17:02 UTC, merged